favicon: /assets/img/identity/favicon.svg
primaryLogo: /assets/img/identity/primary-logo-light.svg

main_menu_settings:
  menu_items:
    - title: About Me
      url: /about-me
    - title: Scholarship
      url: /scholarship
    - title: Teaching
      url: /teaching
    - title: Service
      url: /service
    - title: Blog
      url: /blog
    - title: Contact Me
      url: /contact-me


footer_menu_settings:
  menu_items:
    - title: Other Websites
      submenu_items:
      - title: House of Basu-Howard
        url: https://basuhoward.org
        target: _blank
      - title: The Count of Krigsvold
        url: https://krigsvold.org
        target: _blank
      - title: Manor of Dungeon in Kent
        url: https://dungeonmanor.uk
        target: _blank
    - title: 
      submenu_items:
      - title: Grand Duchy of Westarctica
        url: https://www.westarctica.info
      - title: Encyclopedia Westarctica
        url: https://www.westarctica.wiki
      - title: Westarctica, Inc.
        url: https://www.westarctica.org
    - title: Resources
      submenu_items:
      - title: NOAA
        url: https://www.climate.gov
        target: _blank
      - title: United Nations
        url: https://www.un.org/en/climatechange
        target: _blank
      - title: EPA
        url: https://www.epa.gov/climate-change
        target: _blank
    - title: Legal
      submenu_items:
      - title: Privacy
        url: /privacy-policy
      - title: Terms of Use
        url: /terms-of-use
      - title: Copyright
        url: /copyright

other_sites:
  - title: House of Basu-Howard
    url: https://basuhoward.org
    target: _blank
  - title: The Count of Krigsvold
    url: https://krigsvold.org
    target: _blank
  - title: The Manor of Dungeon in Kent
    url: https://dungeonmanor.uk
    target: _blank

notices:
  - title: Disclosure Statement
    url: /disclosure-statement/
  - title: Terms of Use
    url: /terms-of-use/
  - title: Privacy Policy
    url: /privacy-policy/
        
social_media:
  - icon: keybase
    name: Keybase
    url: https://keybase.io/howardjp
  - icon: facebook
    name: Facebook
    url: https://facebook.com/k3jph
  - icon: mastodon
    name: Mastodon
    url: https://mastodon.social/@k3jph
  - icon: instagram
    name: Instagram
    url: https://www.instagram.com/k3jph/
  - icon: linkedin
    name: LinkedIn
    url: https://www.linkedin.com/in/k3jph/
  - icon: youtube
    name: Youtube
    url: https://www.youtube.com/@k3jph
  - icon: github
    name: Github
    url: https://github.com/k3jph
  - icon: amazon
    name: Amazon
    url: https://amazon.com/author/k3jph
  - icon: orcid
    name: ORCiD
    url: https://orcid.org/0000-0003-4530-1547

footer_settings:
  footer_tagline: A website of the House of Basu-Howard
