import {readFile,readdir,stat} from 'node:fs/promises';import path from 'node:path';
const root=process.cwd(),dist=path.join(root,'dist');
async function walk(dir){const out=[];for(const name of await readdir(dir)){const file=path.join(dir,name);(await stat(file)).isDirectory()?out.push(...await walk(file)):out.push(file);}return out;}
const files=await walk(dist),htmlFiles=files.filter(f=>f.endsWith('.html'));const rel=new Set(files.map(f=>`/${path.relative(dist,f).split(path.sep).join('/')}`));
const exists=url=>{const clean=decodeURI(url.split(/[?#]/)[0]);if(!clean||clean==='/')return rel.has('/index.html');return rel.has(clean)||rel.has(`${clean.replace(/\/$/,'')}/index.html`)||rel.has(`${clean.replace(/\/$/,'')}.html`)||rel.has(`${clean}/index.html`);};
const failures=[],warnings=[];let references=0;
for(const file of htmlFiles){const html=await readFile(file,'utf8');const route=`/${path.relative(dist,file).replaceAll(path.sep,'/').replace(/index\.html$/,'')}`;if(/\{%|\{\{/.test(html))failures.push(`${route}: unresolved Liquid`);if(!/<title>[^<]+<\/title>/i.test(html))failures.push(`${route}: missing title`);if(route!=='/laserprj.html'&&!/<link rel="canonical" href="https:\/\/jameshoward\.us\//i.test(html))failures.push(`${route}: missing canonical`);for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const ref=match[1];if(!ref.startsWith('/')||ref.startsWith('//'))continue;references++;if(!exists(ref))failures.push(`${route}: missing ${ref}`);}}
const required=['/index.html','/blog/index.html','/ancestry/index.html','/books/index.html','/honors/index.html','/service/index.html','/software/index.html','/teaching/index.html','/search/index.html','/contact-me.html','/404.html','/feed.xml','/atom.xml','/feed/atom.xml','/sitemap.xml','/sitemap-pages.xml','/sitemap-ancestry.xml','/data/search.json','/CNAME','/robots.txt'];for(const file of required)if(!rel.has(file))failures.push(`missing required output ${file}`);
const unique=[...new Set(failures)];console.log(JSON.stringify({html_routes:htmlFiles.length,static_files:files.length,local_references:references,errors:unique.length,warnings:warnings.length},null,2));if(warnings.length)console.warn(warnings.slice(0,20).join('\n'));if(unique.length){console.error(unique.slice(0,100).join('\n'));process.exit(1);}
